image:
  file: .gitpod.Dockerfile
tasks:
  - init: 'set +x; clear'
    command: |
      function gt() {
        TAG=${1}; git tag --delete ${TAG} 2>/dev/null; git push  --delete origin ${TAG} 2>/dev/null; git tag  ${TAG}; git push --tags
      }
      mkdir ~/.ssh 2>/dev/null
      echo $ID_RSA | base64 --decode > ~/.ssh/id_rsa
      echo $ID_RSA_PUB | base64 --decode > ~/.ssh/id_rsa.pub
      echo $ID_RSA_CERT_PUB | base64 --decode > ~/.ssh/id_rsa-cert.pub
      chmod -R 700 ~/.ssh
