apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
  labels:
    app: none
spec:
  storageClassName: rook-ceph-block-kernel
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

