FROM scratch
ADD distro/squashed-bootstrap.tar.gz /
ADD files/entrypoint-bootstrap.sh /files/entrypoint.sh
ADD files/newbash.sh /usr/bin/bash
RUN chmod 555 /usr/bin/bash

LABEL MAINTAINER "Bob Liotta" <bob@bobdot.me>
ENTRYPOINT [ "/files/entrypoint.sh" ]

RUN /usr/bin/ls /
RUN /usr/bin/sh -c "echo Shell Working"
RUN /usr/bin/rsync --help
RUN /usr/bin/sleep 1
