FROM scratch
ARG TARGETARCH
ENV ARCH $TARGETARCH
ADD "distro/ubuntu-focal-$TARGETARCH-latest.tar.gz" /

LABEL MAINTAINER "Bob Liotta" <bob@262.life>

EXPOSE 8873
ENTRYPOINT [ "/files/entrypoint.sh" ]
