FROM scratch
ARG TARGETARCH
RUN "echo I am running for $TARGETARCH architecture"
ADD "distro/ubuntu-focal-$TARGETARCH-latest.tar.gz" /

LABEL MAINTAINER "Bob Liotta" <bob@262.life>

EXPOSE 8873
ENTRYPOINT [ "/files/entrypoint.sh" ]
