FROM scratch
ARG TARGETARCH
ENV ARCH $TARGETARCH
ADD VERSION /files/VERSION
ADD "distro/squashed-lowcarb-$TARGETARCH.tar.gz" /
ADD files/entrypoint-lowcarb.sh /files/entrypoint.sh
ADD files/newbash.sh /usr/bin/bash

LABEL MAINTAINER "Bob Liotta" <bob@262.life>

RUN ls /bin /usr/bin

RUN echo "-- Testing Begins ---------" \ 
    $$ echo "$ARCH" > /files/ARCH
    && echo "ls /bin ---" \
    && /usr/bin/ls /bin \
    && echo "ls /usr/bin ---" \
    && /usr/bin/ls /usr/bin \
    && echo "ls /files ---" \
    && /usr/bin/ls /files \
    && echo "SHELL TEST ---" \
    && /usr/bin/sh -c "echo Shell Working" \
    && echo "RSYNC TEST ---" \
    && /usr/bin/rsync --version \
    && echo "SLEEP TEST ---" \
    && /usr/bin/sleep 1

ENTRYPOINT [ "/files/entrypoint.sh" ]

