---
apiVersion: apps/v1
kind: {{ .Values.manifest}}
metadata:
  name: bob-bootstrap
  namespace: {{ .Values.namespace}}
  labels:
    k8s-app: bob-bootstrap
spec:
  selector:
    matchLabels:
      name: bob-bootstrap
  template:
    metadata:
      labels:
        name: bob-bootstrap
    spec:
      containers:
      - name: daemonset
        image: "bobdotme/bob-mini:{{ .Chart.Version }}"
        imagePullPolicy: 
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 4Mi
        volumeMounts:
        - name: shared-volume
          mountPath: /usr
        env:
        - name: BOB_SERVICE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      initContainers:
      - name: bootstrap
        image: "bobdotme/bob-bootstrap:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 4Mi
        volumeMounts:
        - name: shared-volume
          mountPath: /usr-sync
      terminationGracePeriodSeconds: 30
      volumes:
      - name: shared-volume
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: bob
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: bob-core
  ports:
    - protocol: TCP
      port: 8873
      targetPort: 8873
      name: sync
---
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob-core
  namespace: {{ .Values.namespace}}
spec:
  selector:
    matchLabels:
      app: bob-core
  serviceName: bob-core
  replicas: 3
  template:
    metadata:
      labels:
        app: bob-core
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: "bobdotme/bob-core:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: bob-core
        ports:
        - containerPort: 8873
          name: sync
          protocol: TCP
        volumeMounts:
        - name: shared-volume
          mountPath: /data
        resources:
          limits:
            memory: "1Gi"
            cpu: "300m"
          requests:
            memory: "1Gi"
            cpu: "300m"
        #securityContext:
        #  privileged: true
      volumes:
      - name: shared-volume
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
