---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bob-bootstrap
  namespace: {{  .Values.namespace default "bob"}}
  labels:
    k8s-app: bob-bootstrap
spec:
  selector:
    matchLabels:
      name: bob-bootstrap
  template:
    metadata:
      labels:
        name: bob-bootstrap
    spec:
      containers:
      - name: daemonset
        image: "bobdotme/bob-mini:{{ .Chart.Version }}"
        imagePullPolicy: 
        resources:
          limits:
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 4Mi
        volumeMounts:
        - name: shared-volume
          mountPath: /usr
      initContainers:
      - name: bootstrap
        image: "bobdotme/bob-bootstrap:{{ .Chart.Version }}"
        imagePullPolicy: {{  .Values.image.pullPolicy default "IfNotPresent"}}
        resources:
          limits:
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 4Mi
        volumeMounts:
        - name: shared-volume
          mountPath: /usr-sync
      terminationGracePeriodSeconds: 30
      volumes:
      - name: shared-volume
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: bob
  namespace: {{  .Values.namespace default "bob"}}
spec:
  selector:
    app: bob-core
  ports:
    - protocol: TCP
      port: 8873
      targetPort: 8873
      name: sync
---
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob-core
  namespace: {{  .Values.namespace default "bob"}}
spec:
  selector:
    matchLabels:
      app: bob-core
  serviceName: bob-core
  replicas: 3
  template:
    metadata:
      labels:
        app: bob-core
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: "bobdotme/bob-core:{{ .Chart.Version }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        name: bob-core
        ports:
        - containerPort: 8873
          name: sync
          protocol: TCP
        resources:
          limits:
            memory: "1Gi"
            cpu: "300m"
          requests:
            memory: "1Gi"
            cpu: "300m"
        securityContext:
          privileged: true
