---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bob-proxy
  namespace: bob
  labels:
    k8s-app: bob-proxy
spec:
  selector:
    matchLabels:
      name: bob-proxy
  template:
    metadata:
      labels:
        name: bob-proxy
    spec:
      containers:
      - name: bob-proxy
        ports:
        - containerPort: 2049
          hostPort: 2049
          name: dummy
          protocol: TCP
        image: "bobdotme/bob-proxy:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: bob
  namespace: bob
spec:
  selector:
    app: bob-core
  ports:
    - protocol: TCP
      port: 2049
      targetPort: 2049
      name: ramdisk
    - protocol: TCP
      port: 22
      targetPort: 22
      name: ssh
    - protocol: TCP
      port: 5201
      targetPort: 5201
      name: iperf3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob-core
  namespace: bob
spec:
  selector:
    matchLabels:
      app: bob-core
  serviceName: bob-core
  replicas: 3
  template:
    metadata:
      labels:
        app: bob-core
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: "bobdotme/bob-core:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: bob-core
        ports:
        - containerPort: 80
          name: dummy
          protocol: TCP
        - containerPort: 2049
          name: nfs-service
          protocol: TCP
        resources:
          limits:
            memory: "1Gi"
            cpu: "300m"
          requests:
            memory: "1Gi"
            cpu: "300m"
        securityContext:
          privileged: true
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
