apiVersion: v1
kind: Pod
metadata:
  name: childs-lenard
  
  labels:
    app: bob
spec:
  terminationGracePeriodSeconds: 20
  containers:
  - image: bobdotme/bob-mini:v0.9.6
    imagePullPolicy: IfNotPresent
    name: childs-lenard
    ports:
    - containerPort: 80
      name: dummy
      protocol: TCP
    resources:
      limits:
        memory: "1Gi"
        cpu: "2"
      requests:
        memory: "1M"
        cpu: "500m"
    volumeMounts:
    
    
    - name: shared-volume
      mountPath: /usr

    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: MY_POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
  restartPolicy: Always
  initContainers:
  - image: bobdotme/bob-bootstrap:v0.9.6
    imagePullPolicy: IfNotPresent
    name: initialize
    resources:
      limits:
        memory: "1Gi"
        cpu: "2"
      requests:
        memory: "1M"
        cpu: "500m"
    volumeMounts:
    - name: shared-volume
      mountPath: /usr-sync
  volumes:
  
  
  - name: shared-volume
    emptyDir: 
      medium: Memory
      sizeLimit: "1Gi"
