#Workflows
name: bash_on_board
on: 
  push:
    tags:
    - "v[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: |
          export POSTFIX=" (Codename: '$(cat CODENAME)')"
          echo "::set-env name=RELEASE_NAME_POSTFIX::$POSTFIX"
      - name: Print Release Version
        run: |
          export RELEASE_VERSION=$(echo $GITHUB_REF | awk -F\/ '{print $3}')
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
          echo "Release Version is $RELEASE_VERSION"
      - name: Create Bundle
        run: |
          bash -c "cd kubectl;  tar zcvf ../bob-plugins.tgz *; cd .."
      - name: Build Action 
        env: # Or as an environment variable
            docker_login: ${{ secrets.DOCKER_ID }}
            docker_token: ${{ secrets.DOCKER_TOKEN }}      
        run: |
          bash -c "chmod 755 ./init.sh; LATEST=true TAG=$RELEASE_VERSION DOCKER_FILE=dockerfiles/Dockerfile       ./init.sh bob-core"
          bash -c "chmod 755 ./init.sh; LATEST=true TAG=$RELEASE_VERSION DOCKER_FILE=dockerfiles/Dockerfile.proxy ./init.sh bob-proxy"
          bash -c "chmod 755 ./init.sh; LATEST=true TAG=$RELEASE_VERSION DOCKER_FILE=dockerfiles/Dockerfile.mini  ./init.sh bob"
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          CHANGELOG_FILE: "docs/changes.md"
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            testpv.yaml
            bob-plugins.tgz
