#Workflows
name: nightly_release
on: 
  push:
    branches:
      "develop"
jobs:
  nightly-release:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Version
        run: |
          export RELEASE_NAME=$(echo $GITHUB_REF | awk -F\/ '{print $3}')
          echo "::set-env name=RELEASE_NAME::$RELEASE_NAME"
          echo "Release Version is $RELEASE_VERSION"
      - name: Create Plugins
        run: |
          bash -c "cd kubectl;  tar zcvf ../bob-plugins.tgz *; cd .."
      - name: Build Action 
        env: # Or as an environment variable
            docker_login: ${{ secrets.DOCKER_ID }}
            docker_token: ${{ secrets.DOCKER_TOKEN }}      
        run: |
          bash -c "chmod 755 ./init.sh; LATEST=false TAG=$RELEASE_NAME DOCKERFILE=dockerfiles/Dockerfile       ./init.sh bob-core"
          bash -c "chmod 755 ./init.sh; LATEST=false TAG=$RELEASE_NAME DOCKERFILE=dockerfiles/Dockerfile.proxy ./init.sh bob-proxy"
          bash -c "chmod 755 ./init.sh; LATEST=false TAG=$RELEASE_NAME DOCKERFILE=dockerfiles/Dockerfile.mini  ./init.sh bob"
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          DRAFT_RELEASE: "true"
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          CHANGELOG_FILE: "docs/changes.md"
          PRE_RELEASE: "false"
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
            examples/testpv.yaml
            bob-plugins.tgz
