#Workflows

name: nightly_release
on: 
  push:
    tags:
      - "v0.0.0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Print Release Version
        run: |
          export TEXT="Release X"
          echo "::set-env name=RELEASE_NAME::$TEXT"
          echo "Release Version is $RELEASE_NAME"
      - name: Create Plugins
        run: |
          bash -c "cd kubectl;  tar zcvf ../bob-plugins.tgz *; cd .."
      - name: Build Action 
        env: # Or as an environment variable
            docker_login: ${{ secrets.DOCKER_ID }}
            docker_token: ${{ secrets.DOCKER_TOKEN }}      
        run: |
          echo "test"
#          bash -c "chmod 755 ./init.sh; LATEST=false TAG=$RELEASE_NAME DOCKERFILE=dockerfiles/Dockerfile       ./init.sh bob-core"
#          bash -c "chmod 755 ./init.sh; LATEST=false TAG=$RELEASE_NAME DOCKERFILE=dockerfiles/Dockerfile.proxy ./init.sh bob-proxy"
#          bash -c "chmod 755 ./init.sh; LATEST=false TAG=$RELEASE_NAME DOCKERFILE=dockerfiles/Dockerfile.mini  ./init.sh bob"
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          DRAFT_RELEASE: "true"
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          CHANGELOG_FILE: "docs/changes.md"
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            examples/testpv.yaml
            bob-plugins.tgz
