name: telegram push
on: [push]
 
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          A new ${{ github.event_name }} event by ${{ github.actor }} repo ${{ github.repository }} 
            - ${{ github.sha }}
